# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-08 12:10
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_data', django.contrib.postgres.fields.jsonb.JSONField(db_index=True)),
            ],
        ),
    ]
